### PR TITLE
Fixed getLatestVersion() sometimes using wrong field

### LINKED ISSUE #109: Work with ASM8.0 AsmClassFactory.getLatestVersion() return an deprecated value ASM9_EXPERIMENTAL
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.glassfish.rmic.Main.getEnv(Main.java:475)
at org.glassfish.rmic.Main.doCompile(Main.java:491)
at org.glassfish.rmic.Main.compile(Main.java:156)
at sun.rmi.rmic.Main.main(Main.java:33)
Caused by: java.lang.IllegalStateException: ASM9_EXPERIMENTAL can only be used by classes compiled with --enable-preview
at org.objectweb.asm.Constants.checkIsPreview(Constants.java:217)
at org.objectweb.asm.Constants.checkAsmExperimental(Constants.java:189)
at org.objectweb.asm.ClassVisitor.(ClassVisitor.java:79)
at org.objectweb.asm.ClassVisitor.(ClassVisitor.java:57)
at org.glassfish.rmic.asm.AsmClassFactory$ClassDefinitionVisitor.(AsmClassFactory.java:112)
at org.glassfish.rmic.asm.AsmClassFactory.loadDefinition(AsmClassFactory.java:96)
at org.glassfish.rmic.tools.javac.BatchEnvironment.loadFile(BatchEnvironment.java:476)
at org.glassfish.rmic.tools.javac.BatchEnvironment.loadDefinition(BatchEnvironment.java:577)
at org.glassfish.rmic.tools.java.ClassDeclaration.getClassDefinition(ClassDeclaration.java:127)
at org.glassfish.rmic.iiop.BatchEnvironment.(BatchEnvironment.java:86)
... 8 more
Cannot instantiate class org.glassfish.rmic.iiop.BatchEnvironment
Exception in thread "main" java.lang.NullPointerException
at org.glassfish.rmic.Main.doCompile(Main.java:492)
at org.glassfish.rmic.Main.compile(Main.java:156)
at sun.rmi.rmic.Main.main(Main.java:33)

### PR DESCRIPTION
**Pull request by dmatej**
* Fixed #109 
* The reflection was too permissive and sometimes could use preview or experimental Java version.
* I also updated returned versions so they would reflect our dependencies.

### CODE REVIEW

File: rmic/src/test/java/org/glassfish/rmic/asm/AsmClassFactoryTest.java [hunk 1]
```diff
@@ -41,6 +40,6 @@ public void canRetrieveLatestAsmVersion() {
 
     @Test
     public void canRetrieveLatestSupportedClassVersion() {
-        assertThat(AsmClassFactory.getLatestClassVersion(), greaterThan(Opcodes.V25));
+        assertThat(AsmClassFactory.getLatestClassVersion(), equalTo(Opcodes.V26));
```
Comment (pzygielo) [inline rmic/src/test/java/org/glassfish/rmic/asm/AsmClassFactoryTest.java:43]: - I've deliberately changed to `gt` in #250 to not need to update with every ASM bump.

Comment (pzygielo) [reply rmic/src/test/java/org/glassfish/rmic/asm/AsmClassFactoryTest.java:43]: But maybe this was mistake to do so.

**Review by pzygielo — APPROVED** [review]

File: rmic/src/test/java/org/glassfish/rmic/asm/AsmClassFactoryTest.java (hunk 1 above)
Comment (dmatej) [reply rmic/src/test/java/org/glassfish/rmic/asm/AsmClassFactoryTest.java:43]: I know, it was justified when you were alone for the whole project. I rather want to know about important changes coming from dependencies. Ant there was the issue with experimental and prerelease fields, the name seems to change between versions. So I made the field evaluation more strict. Maybe we could visit the project and add some static method to return the maximal version, so then we would not need the reflection at all.
